"""Self-contained browser dashboard served by the FastAPI application."""

DASHBOARD_HTML = r"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Commodity Pricing Engine</title><style>
:root{--bg:#07111f;--panel:#101d2f;--line:#263b55;--text:#e8f1fb;--muted:#8fa7c2;--cyan:#22d3ee;--green:#4ade80;--amber:#fbbf24}
*{box-sizing:border-box}body{margin:0;background:linear-gradient(145deg,#06101c,#0b1728);color:var(--text);font:14px system-ui,Segoe UI,sans-serif}
header{padding:24px 30px;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;align-items:center}h1{font-size:22px;margin:0}h2{font-size:15px;margin:0 0 14px;color:#c6dcf3}.tag{color:var(--green)}
main{display:grid;grid-template-columns:340px 1fr;gap:18px;padding:18px;max-width:1400px;margin:auto}.panel{background:rgba(16,29,47,.94);border:1px solid var(--line);border-radius:12px;padding:18px;box-shadow:0 10px 25px #0004}
label{display:block;color:var(--muted);margin:11px 0 5px}.row{display:grid;grid-template-columns:1fr 1fr;gap:10px}input,select{width:100%;background:#091526;color:var(--text);border:1px solid #38516d;border-radius:7px;padding:9px}
button{width:100%;margin-top:17px;padding:11px;border:0;border-radius:8px;background:linear-gradient(90deg,#0891b2,#2563eb);color:white;font-weight:700;cursor:pointer}button:disabled{opacity:.5}.content{display:grid;gap:18px}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.metric{background:#091526;border-radius:9px;padding:14px}.metric span{display:block;color:var(--muted);font-size:12px}.metric strong{display:block;margin-top:6px;font-size:21px;color:var(--cyan)}
table{width:100%;border-collapse:collapse}th,td{text-align:right;padding:9px;border-bottom:1px solid var(--line)}th:first-child,td:first-child{text-align:left}.market-row{cursor:pointer}.market-row:hover{background:#162a42}.up{color:var(--green)}
.greeks{display:grid;grid-template-columns:repeat(5,1fr);gap:9px}.greek{background:#091526;padding:11px;border-radius:8px;text-align:center}.greek small{color:var(--muted);display:block}.greek b{font-size:16px}.status{color:var(--muted);margin-top:10px;min-height:20px}.error{color:#fb7185}canvas{width:100%;height:190px;background:#091526;border-radius:8px}.links a{color:var(--cyan);margin-left:14px;text-decoration:none}
@media(max-width:850px){main{grid-template-columns:1fr}.metrics{grid-template-columns:repeat(2,1fr)}.greeks{grid-template-columns:repeat(2,1fr)}}
</style></head><body>
<header><div><h1>Commodity Derivatives Pricing Engine</h1><div class="tag">● LIVE SIMULATED MARKET</div></div><div class="links"><a href="/docs">API Docs</a><a href="/report/latency">Live Latency</a><a href="/report/comparison">Performance & Accuracy</a></div></header>
<main><section class="panel"><h2>PRICING SIMULATION</h2>
<label>Commodity contract</label><select id="symbol"><option value="GC">Gold (GC)</option><option value="SI">Silver (SI)</option><option value="CL" selected>Crude Oil (CL)</option><option value="NG">Natural Gas (NG)</option></select>
<label>Pricing model</label><select id="model"><option value="black76">Black-76 — fast path</option><option value="asian_gbm">Asian GBM — Monte Carlo</option><option value="asian_ou">Asian OU — mean reverting</option></select>
<div class="row"><div><label>Strike</label><input id="strike" type="number" step="any" value="80"></div><div><label>Maturity (years)</label><input id="maturity" type="number" step="0.01" value="0.5"></div></div>
<label>Option type</label><select id="option_type"><option value="call">Call</option><option value="put">Put</option></select>
<div id="mc" style="display:none"><div class="row"><div><label>Paths</label><input id="paths" type="number" value="100000"></div><div><label>Time steps</label><input id="steps" type="number" value="64"></div></div><div id="ou" style="display:none" class="row"><div><label>Kappa</label><input id="kappa" type="number" step="0.1" value="2.5"></div><div><label>Long-term level</label><input id="theta" type="number" step="any" placeholder="Current price"></div></div></div>
<button id="priceBtn">RUN PRICING SIMULATION</button><div id="status" class="status">Choose inputs and run the simulation.</div></section>
<section class="content"><div class="panel"><h2>PRICING RESULT</h2><div class="metrics"><div class="metric"><span>Option price</span><strong id="price">—</strong></div><div class="metric"><span>Latency</span><strong id="latency">—</strong></div><div class="metric"><span>Implied volatility</span><strong id="vol">—</strong></div><div class="metric"><span>MC standard error</span><strong id="se">—</strong></div></div><h2 style="margin-top:18px">GREEKS</h2><div id="greeks" class="greeks"><div class="status">Available for Black-76</div></div></div>
<div class="panel"><h2>LIVE MARKET STATE — click a row to select</h2><table><thead><tr><th>Contract</th><th>Futures price</th><th>Base volatility</th><th>Version</th></tr></thead><tbody id="market"></tbody></table></div>
<div class="panel"><h2>SIMULATION PRICE HISTORY</h2><canvas id="chart" width="900" height="190"></canvas></div></section></main>
<script>
const $=id=>document.getElementById(id), history=[];let markets={};
function fmt(x,n=4){return Number(x).toLocaleString(undefined,{minimumFractionDigits:n,maximumFractionDigits:n})}
function syncModel(){const m=$('model').value;$('mc').style.display=m==='black76'?'none':'block';$('ou').style.display=m==='asian_ou'?'grid':'none'}
function syncSymbol(){const m=markets[$('symbol').value];if(m)$('strike').value=Number(m.futures_price).toFixed(m.futures_price<10?2:1)}
async function loadMarket(){try{const rows=await(await fetch('/market')).json();markets=Object.fromEntries(rows.map(x=>[x.symbol,x]));$('market').innerHTML=rows.map(x=>`<tr class="market-row" data-symbol="${x.symbol}"><td>${x.symbol}</td><td class="up">${fmt(x.futures_price,x.futures_price<10?3:2)}</td><td>${fmt(x.volatility*100,2)}%</td><td>${x.version}</td></tr>`).join('');document.querySelectorAll('.market-row').forEach(r=>r.onclick=()=>{$('symbol').value=r.dataset.symbol;syncSymbol()})}catch(e){$('status').textContent='Market connection failed: '+e.message}}
function draw(){const c=$('chart'),dpr=window.devicePixelRatio||1,w=Math.max(c.clientWidth,300),h=190;c.width=Math.round(w*dpr);c.height=Math.round(h*dpr);const x=c.getContext('2d');x.setTransform(dpr,0,0,dpr,0,0);x.clearRect(0,0,w,h);x.font='12px system-ui,Segoe UI,sans-serif';if(!history.length){x.fillStyle='#8fa7c2';x.fillText('Run pricing simulations to draw results.',25,35);return}const vals=history.map(a=>a.price),lo=Math.min(...vals),hi=Math.max(...vals),span=hi-lo||Math.max(Math.abs(hi)*.02,1),left=28,right=w-24,top=20,bottom=h-30,points=history.map((v,i)=>({x:history.length===1?(left+right)/2:left+i*(right-left)/(history.length-1),y:top+(hi-v.price)/span*(bottom-top)}));x.strokeStyle='#263b55';x.lineWidth=1;x.beginPath();x.moveTo(left,top);x.lineTo(left,bottom);x.lineTo(right,bottom);x.stroke();if(points.length>1){x.strokeStyle='#22d3ee';x.lineWidth=3;x.beginPath();points.forEach((p,i)=>i?x.lineTo(p.x,p.y):x.moveTo(p.x,p.y));x.stroke()}x.fillStyle='#22d3ee';for(const p of points){x.beginPath();x.arc(p.x,p.y,4,0,Math.PI*2);x.fill()}x.fillStyle='#e8f1fb';x.fillText(`min ${fmt(lo)}   max ${fmt(hi)}   observations ${history.length}`,left,h-9)}
async function run(){const button=$('priceBtn');button.disabled=true;$('status').className='status';$('status').textContent='Calculating…';const body={symbol:$('symbol').value,model:$('model').value,strike:+$('strike').value,maturity:+$('maturity').value,option_type:$('option_type').value,paths:+$('paths').value,steps:+$('steps').value,kappa:+$('kappa').value};if($('theta').value)body.theta=+$('theta').value;try{const response=await fetch('/price',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),data=await response.json();if(!response.ok)throw new Error(data.detail||'Pricing failed');$('price').textContent=fmt(data.price);$('latency').textContent=fmt(data.latency_ms)+' ms';$('vol').textContent=fmt(data.volatility*100,2)+'%';$('se').textContent=data.standard_error==null?'Analytical':fmt(data.standard_error);$('status').textContent=`Completed with ${data.model}${data.cached?' (cache hit)':''}, market version ${data.market_version}.`;if(data.greeks){$('greeks').innerHTML=Object.entries(data.greeks).map(([k,v])=>`<div class="greek"><small>${k.toUpperCase()}</small><b>${fmt(v,6)}</b></div>`).join('')}else $('greeks').innerHTML='<div class="status">Monte Carlo result — analytical Greeks are not applicable.</div>';history.push({price:data.price});if(history.length>50)history.shift();draw()}catch(e){$('status').className='status error';$('status').textContent=e.message}finally{button.disabled=false}}
$('model').onchange=syncModel;$('symbol').onchange=syncSymbol;$('priceBtn').onclick=run;window.addEventListener('resize',draw);syncModel();draw();loadMarket();setInterval(loadMarket,1000);
</script></body></html>"""
